// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hr.simonsw.domain;

import com.hr.simonsw.domain.SimonswResource;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SimonswResource_Roo_Configurable {
    
    declare @type: SimonswResource: @Configurable;
    
}
